Algoritmo "ExemploLacoRepeticaoPara"
// Matéria: [Lógica de Programação]
// Professor: Jailson Costa dos Santos
// Descrição   : Esse programa executa o laço de repetição "Para"
// Autor(a)    : Laura Scorsafava
// Data atual  : 17/09/2025
Var
   // Seção de Declarações das variáveis

   contadora: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   para contadora de 1 ate 10 passo 1 faca
      Escreval ("Laura")
   fimpara

Fimalgoritmo