Algoritmo "ExemploLacoPara"
// Matéria: [Lógica de Programação]
// Professor: Jailson Costa dos Santos 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/09/2025
Var
// Seção de Declarações das variáveis 

contadora: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para contadora de 1 ate 10 passo 1 faca
escreval (contadora)
fimpara

Fimalgoritmo